### ISSUE TITLE
Panic without parameters provided

### ISSUE THREAD

**Issue by dinosn** [iustin24/chameleon#1]
Hi, 

  One small feature request, running the application without any parameters should point to help. 

```
root@system:~# chameleon 
thread 'main' panicked at 'No URL supplied.', src/main.rs:31:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Regards,
Nicolas

**Comment by iustin24** [comment]
Hi @dinosn,

Thanks for submitting the project's first issue!  🎉

I removed the panic when no URL is supplied and modified it to display the following error message:
`No URL supplied. Please use '-u' to supply a url. `

https://github.com/iustin24/chameleon/commit/3d76c98deb9d3ac0b6e109145d69c88a0994a239

Thanks again!
