### ISSUE TITLE
#Chrome launched, but didn't give us a WebSocket URL before we timed out

### ISSUE THREAD

**Issue by JawadMahdiBD** [iustin24/chameleon#10]
chameleon -u http://testphp.vulnweb.com/ -a

While running the basic command, I encountered this issue

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chrome launched, but didn't give us a WebSocket URL before we timed out', /cargo/git/checkouts/wappalyzer-e32a3fb79f4ccad3/2c102ca/src/lib.rs:98:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I tried to fix it by using this command 
sudo apt-get install libxss1

Still the same issue exists.

**Comment by iustin24** [comment]
That error usually means the chrome binary errors out.
Can you try running the binary and check if there are any errors? It should be installed at this location:
`~/.local/share/headless-chrome/linux-634997/chrome-linux/chrome`

**Comment by JawadMahdiBD** [comment]
The issue got fixed by this command - apt --fix-broken install
