### ISSUE TITLE
chameleon failed to open after installation

### ISSUE THREAD

**Issue by TaqwaGuy** [iustin24/chameleon#11]
after i finished installing chameleon, i tried opening it by using the command "chameleon --help" but it failed to open, it displayed bash command not found.
NB: im on MacBook Air (13-inch, 2017)
thanks

**Comment by iustin24** [comment]
Hi @TaqwaGuy,

The install script will download the file into the current directory. Try running `./chameleon` instead of `chameleon`. Please let me know if you still have issues!
