### ISSUE TITLE
Nodejs.txt does not exist in default installation and causes the scan to fail.

### ISSUE THREAD

**Issue by j0eblow** [iustin24/chameleon#12]
```
Detected Technology - Node.js ( /home/kali/.config/chameleon/wordlists/Nodejs.txt )

thread 'main' panicked at 'Unable to read wordlist.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:83:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Creating a dummy file at `/home/kali/.config/chameleon/wordlists/Nodejs.txt` fixes the issue.

**Comment by iustin24** [comment]
Hi @j0eblow,

Thanks for pointing this out!
I have removed NodeJS from the config file since there's no wordlist for it currently. If Ill find a wordlist for it, I will add it back.
