### ISSUE TITLE
Allow the use of other HTTP verb

### ISSUE THREAD

**Issue by JoshuaMart** [iustin24/chameleon#15]
Hi iustin24,
Thanks for this tool ! 

Would it be possible to add an option to specify the HTTP verbs to use ? By default GET is used but I think it would be nice to have an option to use other verbs like POST.

Regards

**Comment by iustin24** [comment]
Hi @JoshuaMart,

Thanks for the suggestion!
I added the option to change the HTTP verb using the `-X` flag (aca555bb3fe2afa5e543f70024a87f20d0eae38d) . It's also possible to use multiple HTTP verbs like so:

```
chameleon -u https://google.com -X GET,POST
```

These changes will be included in the next release ( v1.1 ). If you want to start using them sooner, you can either clone the project and build using cargo build --release, or use cargo install --git https://github.com/iustin24/chameleon.

Thanks again for the suggestions!
