### ISSUE TITLE
sudo: chameleon: command not found / bash: chameleon: command not found

### ISSUE THREAD

**Issue by mysanismine** [iustin24/chameleon#17]
Well I'm Windows user so idk anything about linux, now installed linux and face sudo: chameleon: command not found or bash chameleon: command not found. Any advice? I can't find anything useful/fix this problam on internet.

**Comment by iustin24** [comment]
Hi @AliAlShammari,

If you installed it using the bash script you should use `./chameleon`, since the script downloads the binary in the current directory. 

Also discussed in a previous issue https://github.com/iustin24/chameleon/issues/11 .

Let me know if you still have issues!

**Comment by mysanismine** [comment]
![issue](https://user-images.githubusercontent.com/45455533/207118300-e2306efb-b179-456d-a15e-5079d94eea5b.PNG)

hmmmm not fixed, any tip?

**Comment by mysanismine** [comment]
Nah fixed with bash script `./chameleon` thanks budy. Great tool!
