### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by gprime31** [iustin24/chameleon#5]
Nice tool!
but i keep getting this error while on vpn only. ( must be a timeout thing)
![2022-09-12_11-57](https://user-images.githubusercontent.com/44535257/189700941-dae4775f-a140-4297-b1e1-97923ed1afd1.png)

**Comment by iustin24** [comment]
Hi @gprime31,

Does this happen on all urls? Or only when the response doesn't include the content-length?

**Comment by gprime31** [comment]
seems like it's only when the response doesn't include the content-length.
